services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
  backend:
    container_name: python
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  frontend:
    container_name: nodejs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
