# Generated by Django 4.1.7 on 2023-03-05 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipeline', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='uploader',
            old_name='uploader',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='viewer',
            old_name='viewer',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('user', 'pipeline')},
        ),
        migrations.AlterUniqueTogether(
            name='uploader',
            unique_together={('user', 'pipeline')},
        ),
        migrations.AlterUniqueTogether(
            name='viewer',
            unique_together={('user', 'pipeline')},
        ),
    ]
