# Generated by Django 4.1.7 on 2023-03-03 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpipeline',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 6, 37, 33, 56301, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 6, 37, 33, 56301, tzinfo=datetime.timezone.utc)),
        ),
    ]
