# Generated by Django 4.1.7 on 2023-02-28 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='upload_frequency',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
