# Generated by Django 4.1.7 on 2023-03-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_request_pipeline_alter_request_accept_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
