# Generated by Django 4.1.7 on 2023-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_historicalpipeline_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpipeline',
            name='created',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
