# Generated by Django 4.1.7 on 2023-04-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.TextField()),
                ('attribute_type', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Varchar'), (2, 'Int'), (3, 'Date'), (4, 'Boolean'), (5, 'Datetime'), (6, 'Enum')], default=0)),
                ('nullable', models.BooleanField(default=False)),
                ('pipeline_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipelinefile')),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
