# Generated by Django 4.1.7 on 2023-04-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.TextField()),
                ('column_type', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'String'), (2, 'Integer'), (3, 'Float'), (4, 'Boolean'), (5, 'Date'), (6, 'Address'), (7, 'Email')], default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
            ],
        ),
    ]
