# Generated by Django 4.1.7 on 2023-03-14 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=40)),
                ('upload_frequency', models.DurationField(default=datetime.timedelta)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_stable', models.BooleanField(default=True)),
                ('hard_deadline', models.BooleanField(default=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('update_reason', models.TextField(null=True)),
                ('accept_changes', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('response', models.TextField(null=True)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
