# Generated by Django 4.1.7 on 2023-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_delete_request'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='request',
            name='pipeline',
            field=models.ManyToManyField(null=True, to='pipeline.pipeline'),
        ),
    ]
