# Generated by Django 4.1.7 on 2023-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_delete_request'),
        ('request', '0002_remove_request_pipeline_request_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pipeline',
            field=models.ManyToManyField(to='pipeline.pipeline'),
        ),
    ]
