# Generated by Django 4.1.7 on 2023-03-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_delete_request'),
        ('request', '0003_alter_request_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='request',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline'),
        ),
    ]
