# Generated by Django 4.1.7 on 2023-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_request_pipeline_request_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
