name: Start Cloud Run Service

on:
  push:
    branches:
      - deployment-test

jobs:
  start_service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Authenticate Google Cloud service
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/671371757704/locations/global/workloadIdentityPools/githubactions/providers/github
          service_account: github-actions@dataplatformcolgate.iam.gserviceaccount.com
      - name: Deploy Frontend Cloud Run service
        run: |-
         gcloud run deploy frontend-test --region=us-central1 --platform=managed --port=3000 --memory=8Gi --cpu=4000m --service-account=github-actions@dataplatformcolgate.iam.gserviceaccount.com --allow-unauthenticated --source deployment-test/serve-frontend.yml
      - name: Deploy Backend Cloud Run service
        run: |-
          gcloud run deploy backend-test --region=us-central1 --platform=managed --port=8000 --memory=8Gi --cpu=4000m --service-account=github-actions@dataplatformcolgate.iam.gserviceaccount.com --allow-unauthenticated --source deployment-test/serve-backend.yml


     
