name: Project CI

on:
  push:
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: development_secret
      DEBUG: 1
      DB_HOST: ${{ secrets.HOST }}
      DB_NAME: ${{ secrets.NAME }}
      DB_USER: ${{ secrets.USER }}
      DB_PASS: ${{ secrets.PASSWORD }}

      POSTGRES_DB: ${{ secrets.NAME }}
      POSTGRES_USER: ${{ secrets.USER }}
      POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up containers
        run: docker-compose up -d
      - name: Run Django tests
        run: docker exec django python manage.py test
      - name: Trigger pull request
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-pull-request
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      # - name: git checkout
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create pull request
      #   id: open-pr
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     destination_branch: ${{ github.event.repository.default_branch }}
      #     pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
      #     pr_body: "Automated Pull Request"
