name: Project CI
on:
  push:
  pull_request:
    branches:
      - development
      - main
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: development_secret
      DEBUG: 1
      DB_HOST: ${{ secrets.HOST }}
      DB_NAME: ${{ secrets.NAME }}
      DB_USER: ${{ secrets.USER }}
      DB_PASS: ${{ secrets.PASSWORD }}

      POSTGRES_DB: ${{ secrets.NAME }}
      POSTGRES_USER: ${{ secrets.USER }}
      POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up containers
        run: docker-compose up -d --build

      - name: Run Django tests
        run: docker exec django python manage.py test

      - name: Call merge workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'development' }}
        with:
          workflow: ./merge-development.yml
          ref: ${{ github.ref_name }}

      - name: Call frontend push
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          workflow: google-cloudrun-docker-frontend.yml
          ref: ${{ github.ref_name }}

      - name: Call backend push
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          workflow: google-cloudrun-docker-backend.yml
          ref: ${{ github.ref_name }}

      - name: Call deploy
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          workflow: google-cloudrun-start.yml
          ref: ${{ github.ref_name }}