name: Project CI
on:
  push:
    branches:
      - development
      - main
      - dev/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTHENTICATION: ${{ secrets.AUTHENTICATION }}
      DEBUG: 0
      DB_HOST: ${{ secrets.HOST }}
      DB_NAME: ${{ secrets.NAME }}
      DB_USER: ${{ secrets.USER }}
      DB_PASS: ${{ secrets.PASSWORD }}
      POSTGRES_DB: ${{ secrets.NAME }}
      POSTGRES_USER: ${{ secrets.USER }}
      POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
      ENVIRONMENT: development
      CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v3
      - name: Build containers
        run: docker-compose up -d --build
      - name: Run Django tests
        run: docker exec django python manage.py test
      - name: Merge workflow
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'development' }}
        with:
          workflow: merge-development.yml
          ref: ${{ github.ref_name }}
      - name: Push backend container
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          workflow: google-cloudrun-docker-backend.yml
          ref: ${{ github.ref_name }}