name: Django CI

on:
  push:
    branches:
      - dev/docker
  pull_request:
    branches:
      - dev/docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: development_secret
      DEBUG: 1
      DB_HOST: ${{ secrets.HOST }}
      DB_NAME: ${{ secrets.NAME }}
      DB_USER: ${{ secrets.USER }}
      DB_PASS: ${{ secrets.PASSWORD }}

      POSTGRES_DB: ${{ secrets.NAME }}
      POSTGRES_USER: ${{ secrets.USER }}
      POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up docker compose
        run: docker-compose up -d
      - name: Run Django tests
        run: docker exec django python manage.py test
