# https://www.jessesquires.com/blog/2022/03/26/gh-action-merge-release-to-main/
name: Merge development into Main

on:
  workflow_run:
    workflows: ["Project CI"]
    types:
      - completed

jobs:
  main:
    name: Pull request into main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
