apiVersion: serving.knative.dev/v1
kind: Service
env:
  PROJECT_ID: dataplatformcolgate
  GAR_LOCATION: us-east4
  SERVICE: frontend-image
  REGION: Northern Virginia
  REPOSITORY: colgate-repo
metadata:
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: cd4df585-8c3f-4ae3-9db1-12889e4a3125
    serving.knative.dev/creator: cae26@njit.edu
    serving.knative.dev/lastModifier: cae26@njit.edu
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
  name: frontend-image
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1000'
        run.googleapis.com/client-name: cloud-console
    
    spec:
      containerConcurrency: 80
      containers:
      - image:${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
        ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
      serviceAccountName: github-actions@dataplatformcolgate.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
